server:
  port: 8088
  servlet:
   context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    timeout: 10000
    database: 0
image:
  server:
    location: /Users/yangds/Desktop/img/
    port: 8087