server:
  port: 8080
  servlet:
   context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useUnicode=true&characterEncoding=utf8
    username: admin
    password: admin
image:
  server:
    location: /Users/yangds/Desktop/img/
    ip: 127.0.0.1
    port: 8088